trunk/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::prefix('admin', function ($routes) {
    $routes->fallbacks('DashedRoute');
});

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Home', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});


/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

trunk/src/Model/Entity/ProductDetail.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;

class ProductDetail extends Entity
{
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];

    protected function _getIsSellFlag()
    {
        return ($this->sell_flag) ? __('TXT_YES') : __('TXT_NO');
    }

    protected function _getIsPurchaseFlag()
    {
        return ($this->purchase_flag) ? __('TXT_YES') : __('TXT_NO');
    }
}

trunk/src/Controller/ProductDetailsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Network\Exception\NotFoundException;

class ProductDetailsController extends AppController
{
    private $en;

    public function initialize() {
        parent::initialize();
        $this->loadModel('Products');
        $this->en = $this->request->session()->read('tb_field');
    }

    public function index()
    {
        $options = [];
        $keyword = '';
        $product = '';
        if ($this->request->query('product_id')) {
            $product_id = $this->request->query('product_id');
            $options[] = [
                'product_id' => $product_id,
            ];
            $product = $this->Products->get($product_id);
        }
        if ($this->request->query('keyword')) {
            $keyword = $this->request->query('keyword');
            $options[] = [
                'OR' => [
                    'ProductDetails.description LIKE' => '%'.trim($keyword).'%',
                    'ProductDetails.remark LIKE' => '%'.trim($keyword).'%',
                ],
            ];
        }
        if ($this->request->query('inactive')) {
            $options[] = [
                'is_suspend' => 1,
            ];
        }
        $this->paginate = [
            'conditions' => $options,
            'limit' => $this->request->query('displays') ? $this->request->query('displays') : '10',
            'contain' => [
                'Products' => [
                    'ProductBrands' => ['Manufacturers'],
                ],
                'Packings' => [
                    'sort' => ['Packings.name_en' => 'asc'],
                ],
                'SingleUnits',
                'PackSizes',
                'LogisticTemperatures',
            ],
            'sortWhitelist' => [
                'Packings.name_en',
                'pack_size',
                'SingleUnits.name_en',
                'single_unit_size',
                'sale_flag',
                'purchase_flag',
                'Products.code',
                'ProductDetails.type',
                'Products.name',
                'Products.name_en',
                'Manufacturers.name',
            ],
        ];
        if (!empty($keyword)) {
            $this->paginate['contain']['SingleUnits'] = function($q) use($keyword) {
                return $q->where([
                    'or' => [
                        'SingleUnits.name LIKE' => '%' . $keyword . '%',
                        'SingleUnits.name_en LIKE' => '%' . $keyword . '%',
                    ],
                ]);
            };
            $this->paginate['contain']['LogisticTemperatures'] = function($q) use($keyword) {
                return $q->where([
                    'or' => [
                        'SingleUnits.name LIKE' => '%' . $keyword . '%',
                        'SingleUnits.name_en LIKE' => '%' . $keyword . '%',
                    ],
                ]);
            };
            $this->paginate['contain']['PackSizes'] = function($q) use($keyword) {
                return $q->where([
                    'or' => [
                        'SingleUnits.name LIKE' => '%' . $keyword . '%',
                        'SingleUnits.name_en LIKE' => '%' . $keyword . '%',
                    ],
                ]);
            };
        }
        $data = [
            'data' => $this->paginate($this->ProductDetails),
            'paging' =>  $this->request->param('paging')['ProductDetails']['pageCount'],
            'product' => $product,
            'locale' => $this->en,
        ];
        $this->set($data);
    }

    public function create()
    {
        $data = $this->ProductDetails->newEntity();
        if ($this->request->is('post')) {
            $data = $this->ProductDetails->patchEntity($data, $this->request->data);
            if ($this->ProductDetails->save($data)) {
                $this->redirect([
                    'action' => 'index',
                    '?' => [
                        'product_id' => $data->product_id,
                    ],
                ]);
            }
        }
        $pack_sizes = $this->getPackSizeList();
        $single_units = $this->getSingleUnitList();
        $packings = $this->getPackingList();
        $temperaturers = $this->getTemperaturerList();

        $txt_register = $this->Common->txtRegister();
        $this->set(compact('data', 'pack_sizes', 'single_units', 'packings', 'temperaturers', 'txt_register'));
    }

    public function edit($id)
    {
        $data = $this->ProductDetails->get($id);
        if ($this->request->is(['post', 'put'])) {
            $data = $this->ProductDetails->patchEntity($data, $this->request->data);
            if ($this->ProductDetails->save($data)) {
                $this->redirect([
                    'action' => 'index',
                    '?' => [
                        'product_id' => $data->product_id,
                    ],
                ]);
            }
        }
        $pack_sizes = $this->getPackSizeList();
        $single_units = $this->getSingleUnitList();
        $packings = $this->getPackingList();
        $temperaturers = $this->getTemperaturerList();

        $txt_edit = $this->Common->txtEdit();
        $this->set(compact('data', 'pack_sizes', 'single_units', 'packings', 'temperaturers', 'txt_edit'));
    }

    public function delete()
    {
        if (!$this->request->is('ajax')) {
            throw new NotFoundException();
        }
        $this->viewBuilder()->layout('ajax');
        $this->autoRender = false;

        $data = $this->ProductDetails->get($this->request->data['id']);
        if ($this->ProductDetails->delete($data)) {
            echo json_encode([
                'status' => 1,
                'message' => 'success',
            ]);
        }
    }

    public function view($id)
    {
        if (!$this->request->is('ajax')) {
            throw new NotFoundException();
        }
        $this->viewBuilder()->layout('ajax');
        $data = $this->ProductDetails->find()
            ->where(['ProductDetails.id' => $id])
            ->contain([
                'Products' => [
                    'ProductBrands' => ['Manufacturers'],
                ],
                'SingleUnits',
                'Packings',
                'PackSizes',
                'LogisticTemperatures',
            ])->first();
        $data1 = [
            'data' => $data,
            'locale' => $this->en,
        ];
        $this->set($data1);
    }

    public function updateSuspend()
    {
        if (!$this->request->is('ajax')) {
            throw new NotFoundException();
        }
        $this->viewBuilder()->layout('ajax');
        $this->autoRender = false;
        $data = $this->ProductDetails->get($this->request->data['id']);
        $data->is_suspend = ($this->request->data['is_suspend'] == 0 ) ? 1 : 0;

        if ($this->ProductDetails->save($data)) {
            echo json_encode([
                'status' => 1,
                'message' => 'success',
            ]);
        }
    }

    public function getPackSizeList()
    {
        $this->loadModel('PackSizes');
        $data = $this->PackSizes->find('list', [
            'keyField' => 'id',
            'valueField' => 'name' . $this->en,
        ])->order(['PackSizes.name' . $this->en => 'asc'])->toArray();

        return $data;
    }

    public function getSingleUnitList()
    {
        $this->loadModel('SingleUnits');
        $data = $this->SingleUnits->find('list', [
            'keyField' => 'id',
            'valueField' => 'name' . $this->en,
        ])->order(['SingleUnits.name' . $this->en => 'asc'])->toArray();

        return $data;
    }

    public function getPackingList()
    {
        $this->loadModel('Packings');
        $data = $this->Packings->find('list', [
            'keyField' => 'id',
            'valueField' => 'name' . $this->en,
        ])->order(['Packings.name' . $this->en => 'asc'])->toArray();

        return $data;
    }

    public function getTemperaturerList()
    {
        $this->loadModel('LogisticTemperatures');
        $data = $this->LogisticTemperatures->find('list', [
            'keyField' => 'id',
            'valueField' => 'name' . $this->en,
        ])->order(['LogisticTemperatures.name' . $this->en => 'asc'])->toArray();

        return $data;
    }

    public function getList()
    {
        if ($this->request->is('ajax')) {
            $this->autoRender = false;
            $this->response->disableCache();
            $this->response->type('json');
            $this->viewBuilder()->layout(false);

            $data = $this->ProductDetails->find('all')
                ->contain([
                    'SingleUnits',
                    'LogisticTemperatures',
                    'PackSizes',
                ])->toArray();

            $this->response->body(json_encode([
                'status' => 1,
                'message' => 'success',
                'data' => $data,
            ]));
            return $this->response;
        }
    }

    public function productList()
    {
        if ($this->request->is('ajax')) {
            $en = $this->request->session()->read('tb_field');
            $products = $this->ProductDetails->find('all')
                ->contain([
                    'Products' => ['ProductBrands'],
                    'PackSizes',
                    'SingleUnits'
                ])
                ->where(['ProductDetails.is_suspend' => 0]);
            $this->set(compact('products', 'en'));
            $this->set('_serialize', ['products']);
        }
        $this->viewBuilder()->layout('ajax');
    }

    /**
     * list all products details base on product selected.
     */
    public function productDetailsDropdown()
    {
        if ($this->request->is('ajax')) {
            $product_id = $this->request->query('product_id');
            $product_name = $this->request->query('product_name');

trunk/src/Template/ProductDetails/create.ctp
<?php
echo $this->element('Form/product_detail');

trunk/src/Template/ProductDetails/edit.ctp
<?php
echo $this->element('Form/product_detail');

trunk/src/Template/ProductDetails/index.ctp
<div class="search-section" style="margin-bottom: 20px;">
    <?php
    echo $this->Form->create('ProductDetails', [
        'class' => 'form-inline',
        'type' => 'get',
        'name' => 'form_search',
    ]);
    echo $this->Form->input('keyword', [
        'name' => 'keyword',
        'placeholder' => __('USER_SEARCH_KEYWORD'),
        'class' => 'form-control',
        'label' => false,
        'value' => $this->request->query('keyword') ? $this->request->query('keyword') : '',
        'templates' => [
            'inputContainer' => '<div class="form-group">{{content}}</div>',
        ]
    ]);
    echo $this->Form->hidden('product_id', [
        'value' => $this->request->query('product_id') ? $this->request->query('product_id') : '',
    ]);
    $this->SwitchStatus->render();
    echo $this->Form->submit('submit', [
        'style' => 'display: none',
    ]);
    echo $this->Form->end();
    ?>
</div>
<div class="total-pagination" style="padding-bottom: 20px;">
    <?php echo $this->element('display_info'); ?>
</div>
<div class="row search-section" style="margin-bottom: 20px;">
    <?php echo $this->element('display_number'); ?>
    <div class="col-md-6 col-sm-6 text-center">
        <h2 class="title-page"><?php //echo $product->$name; ?></h2>
    </div>
    <?= $this->ActionButtons->btnRegisterNew('ProductDetails', ['product_id' => $this->request->query('product_id')]) ?>
    <div class="clearfix"></div>
</div>
<div class="data-tb-list">
    <?php if ($data): ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>&nbsp;</th>
                <th>
                    <?php
                    echo $this->Paginator->sort('Products.code', __d('product_detail', 'TXT_OLD_CODE')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th>
                    <?php
                    echo $this->Paginator->sort('Manufacturers.name', __d('product_detail', 'TXT_MANUFACTURER')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th>
                    <?php
                    echo $this->Paginator->sort('ProductDetails.type', __d('product_detail', 'TXT_PRODUCT_CATEGORY')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th>
                    <?php
                    echo $this->Paginator->sort('Products.name', __d('product_detail', 'TXT_PRODUCT')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th>
                    <?php
                    echo $this->Paginator->sort('details', __('PRODUCT_DETAILS_TXT_PRODUCT_DETAIL')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <?php if (false) : ?>
                <th>
                    <?php
                    echo $this->Paginator->sort('description', __('PRODUCT_DETAILS_TXT_DESCRIPTION')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <?php endif; ?>
                <th>
                    <?php
                    echo $this->Paginator->sort('purchase_flag', __('PRODUCT_DETAILS_TXT_PURCHASE_AVAILABILITY')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th>
                    <?php
                    echo $this->Paginator->sort('sale_flag', __('PRODUCT_DETAILS_TXT_SALE_AVAILABILITY')); ?>
                    <i class="fa fa-sort-desc" aria-hidden="true"></i>
                </th>
                <th width="1%">&nbsp;</th>
                <th width="1%">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $numbering = $this->Paginator->counter('{{start}}');
            foreach ($data as $item):
            ?>
            <tr data-id="<?php echo h($item->id); ?>">
                <th scope="row">
                    <?php
                    echo $numbering; $numbering++; ?>
                </th>
                <td>
                    <?php
                    echo $this->ActionButtons->disabledText($item->is_suspend) ?>
                </td>
                <td>
                    <?php
                    echo h($item->product->code); ?>
                </td>
                <td>
                    <?php
                    echo $this->Comment->getFieldByLocal($item->product->product_brand->manufacturer, $locale); ?>
                </td>
                <td>
                    <?php
                    echo h($item->type); ?>
                </td>
                <td>
                    <?php
                    echo $this->Comment->getFieldByLocal($item->product->product_brand, $locale); ?>
                </td>
                <td>
                    <?php
                    echo $this->Comment->productAndDetails($item, $locale) ?>
                </td>
                <?php if (false) : ?>
                <td>
                    <?php
                    echo h($item->description) ?>
                </td>
                <?php endif; ?>
                <td><?php echo $item->is_purchase_flag; ?></td>
                <td><?php echo $item->is_sell_flag; ?></td>
                <td data-target="<?php echo ($item->is_suspend) ? 1 : 0; ?>">
                    <?php
                    if ($item->is_suspend == 1) {
                        echo $this->Form->button(BTN_ICON_UNDO, [
                            'class' => 'btn btn-recover btn-sm btn_suspend',
                            'data-name' => 'recover',
                            'escape' => false
                        ]);
                    } else {
                        echo $this->Html->link(BTN_ICON_EDIT, [
                            'controller' => 'product-details',
                            'action' => 'edit', $item->id,
                            '?' => ['product_id' => $this->request->query('product_id')]
                            ], [
                            'class' => 'btn btn-primary btn-sm',
                            'escape' => false
                        ]);
                    }
                    ?>
                </td>
                <td data-target="<?php echo ($item->is_suspend) ? 1 : 0; ?>">
                    <?php
                    if ($item->is_suspend == 1) {
                        if (!empty($item->product_brands) || !empty($item->person_in_charges)) {
                            echo $this->Form->button(BTN_ICON_DELETE, [
                                'class' => 'btn btn-delete btn-sm',
                                'id' => 'btn_delete',
                                'disabled' => 'disabled',
                                'escape' => false
                            ]);
                        } else {
                            echo $this->Form->button(BTN_ICON_DELETE, [
                                'class' => 'btn btn-delete btn-sm',
                                'id' => 'btn_delete',
                                'escape' => false
                            ]);
                        }
                    } else {
                        echo $this->Form->button(BTN_ICON_STOP, [
                            'class' => 'btn btn-suspend btn-sm btn_suspend',
                            'data-name' => 'suspend',
                            'escape' => false
                        ]);
                    }
                    ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
<div class="row row-top-space" style="padding-bottom: 20px;">
    <?php echo $this->element('display_number'); ?>
    <?= $this->element('next_prev') ?>
    <div class="clearfix"></div>
</div>

<!--Modal Suspend-->
<?php echo $this->element('Modal/suspend'); ?>
<!--Modal delete-->
<?php echo $this->element('Modal/delete'); ?>
<!--Modal Detail-->
<?php echo $this->element('Modal/view_detail'); ?>

<script>
    (function(e) {
        var optionData = [];
        get_product_detail_list();
        // typehead_initialize('#keyword', optionData);

        $('body').on('click', '.btn_suspend', function (e) {
            e.stopPropagation();
            var content = $('#modal_suspend');
            var txt = '';
            if ($(this).data('name') === 'recover') {
                $('#btn_suspend_yes').text('<?= __('BTN_RECOVER') ?>');
                txt = '<?= __('MSG_CONFIRM_UNDO_SUSPEND') ?>';
            } else {
                $('#btn_suspend_yes').text('<?= __('BTN_SUSPEND') ?>');
                txt = '<?= __('MSG_CONFIRM_SUSPEND') ?>';
            }

            $(content).find('#btn_suspend_yes').data('id', $(this).closest('tr').data('id'));
            $(content).find('#btn_suspend_yes').data('target', $(this).closest('td').data('target'));
            $(content).find('.modal-body p').html(txt);
            $(content).modal('show');
        });

        $('body').on('click', '#btn_suspend_yes', function (e) {
            var params = {
                id: $(this).data('id'),
                is_suspend: $(this).data('target')
            };
            $.post('<?php echo $this->Url->build('/product-details/update-suspend/'); ?>', params, function (data) {
                if (data.message === 'success') {
                    location.reload();
                }
            }, 'json');
        });

        $('body').on('click', '#btn_delete', function (e) {
            e.stopPropagation();
            var content = $('#modal_delete');
            $(content).find('#btn_delete_yes').attr('data-id', $(this).closest('tr').data('id'));
            $(content).modal('show');
        });

        $('body').on('click', '.table>tbody>tr>td a', function(e) {
            e.stopPropagation();
        });

        $('body').on('click', '.data-tb-list .table>tbody>tr', function (e) {
            $.LoadingOverlay('show');
            var id = $(this).closest('tr').data('id');
            $.get('<?php echo $this->Url->build('/product-details/view/'); ?>' + id, function (data) {
                $.LoadingOverlay('hide');
                $('#modal_detail').find('.modal-body').html(data);
                $('#modal_detail').modal('show');
            }, 'html');
        });

        $('body').on('click', '#btn_delete_yes', function (e) {
            $.post('<?php echo $this->Url->build('/product-details/delete/'); ?>', {id: $(this).data('id')}, function (data) {
                if (data.message === 'success') {
                    location.reload();
                }
            }, 'json');
        });

        $('body').on('click', '.tt-selectable', function (e) {
            $('form[name="form_search"]').submit();
        });

        function get_product_detail_list()
        {
            $.get('<?php echo $this->Url->build('/product-details/get-list'); ?>', function(data) {
                if (data != null && data != undefined) {
                    $.each(data.data, function (i, v) {
                        if (v.description) {
                            optionData.push(v.description);
                        }
                        optionData.push(v.logistic_temperature.name_en);
                        optionData.push(v.logistic_temperature.name);
                        if (v.single_unit) {
                            optionData.push(v.single_unit.name_en);
                            optionData.push(v.single_unit.name);
                        }
                        if (v.tb_pack_sizes) {
                            optionData.push(v.tb_pack_sizes.name_en);
                            optionData.push(v.tb_pack_sizes.name);
                        }
                    });
                }
            }, 'json');
        }

        pageOutOfRange(<?= $paging ?>, '<?= $this->request->query('page') ?>');
        var maxPage = parseInt($('#maxPage').val());
        updatePagination(maxPage);
    })();
</script>

trunk/src/Template/ProductDetails/product_details_dropdown.ctp
<?php
if ($products):
    $output = '<option value="">' . __('TXT_SELECT_PRODUCT_DETAIL') . '</option>';
    $name = 'name' . $en;
    foreach ($products as $product) {
        $detail = $product_name . ' ';
        $detail .= $this->Comment->sizeAndUnit($product, $en);
        $output .= '<option value="' . $product->id . '">' . $detail . '</option>';
    }
    echo $output;
endif;

trunk/src/Template/ProductDetails/product_list.ctp
<?php
echo $this->Comment->allProductAndDetailsAsSelectOptions($products, $en, __d('product_package_detail', 'TXT_SELECT_PRODUCT'));

trunk/src/Template/ProductDetails/view.ctp
<table class="table table-striped tb-prbr-view" id="tb-detail">
    <tbody>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_MANUFACTURER') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $this->Comment->getFieldByLocal($data->product->product_brand->manufacturer, $locale); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_PRODUCT_CATEGORY') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $data->type; ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_PRODUCT') ?> :
            </td>
            <td colspan="2">
                <?php
                $product = $this->Comment->getFieldByLocal($data->product->product_brand, $locale);
                $product .= ' ' . $this->Comment->getFieldByLocal($data->product, $locale);
                echo h($product);
                ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_MODAL_PACKAGE_PACK_SIZE') ?> :
            </td>
            <td colspan="2">
                <?php
                $p_size = $data->pack_size . ' ';
                if ($data->tb_pack_sizes) {
                    $p_size .= empty($data->tb_pack_sizes->unit_name_en) ? $data->tb_pack_sizes->unit_name : $data->tb_pack_sizes->unit_name_en;
                }
                echo h($p_size);
                ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_SINGLE_UNIT_SIZE') ?> :
            </td>
            <td colspan="2">
                <?php
                $s_size = $data->single_unit_size . ' ';
                if ($data->single_unit) {
                    $s_size .= $this->Comment->getFieldByLocal($data->single_unit, $locale);
                }
                echo h($s_size);
                ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_LOGISTIC_TEMPERATURE') ?> :
            </td>
            <td colspan="2">
                <?php
                if ($data->logistic_temperature) {
                    echo $data->logistic_temperature->temperature_range . ' ' . $this->Comment->getFieldByLocal($data->logistic_temperature, $locale);
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'MODAL_PACKAGE_PACKING') ?> :
            </td>
            <td colspan="2">
                <?php
                if ($data->packing) {
                    echo $this->Comment->getFieldByLocal($data->packing, $locale);
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_DESCRIPTION') ?> :
            </td>
            <td colspan="2">
                <textarea readonly="readonly" style="background: none;"><?php echo $data->description; ?></textarea>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_PATIENT_AGREEMENT') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $data->is_patient_agreement ? __d('product_detail', 'TXT_REQUIRED') : ''; ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_IMPORT_CERTIFICATE') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $data->import_certificate ? __d('product_detail', 'TXT_REQUIRED') : ''; ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_PURCHASE_AVAILABILITY') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $data->purchase_flag ? __d('product_detail', 'TXT_YES') : __d('product_detail', 'TXT_NO'); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_SALE_AVAILABILITY') ?> :
            </td>
            <td colspan="2">
                <?php
                echo $data->sale_flag ? __d('product_detail', 'TXT_YES') : __d('product_detail', 'TXT_NO'); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_REMARKS') ?> :
            </td>
            <td colspan="2">
                <textarea readonly="readonly" style="background: none;"><?php echo $data->remark; ?></textarea>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_MODIFIED') ?> :
            </td>
            <td colspan="2">
                <?php
                echo date('Y-m-d', strtotime($data->modified)); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php
                echo __d('product_detail', 'TXT_REGISTERED') ?> :
            </td>
            <td colspan="2">
                <?php
                echo date('Y-m-d', strtotime($data->created)); ?>
            </td>
        </tr>
    </tbody>
</table>